import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './nav-bar'
import { ReduxProvider } from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <ReduxProvider><NavBar/>{children}</ReduxProvider> </body>
    </html>
  )
}
